version: '3.4'

services:
  db:
    container_name: db
    image: mysql:5.7.24
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: my_mysql_db
    ports:
      - '3306:3306'
    volumes:
      - my_volume:/var/lib/mysql
      #- ./db:/docker-entrypoint-initdb.d
    networks:
      - back

  tryexpress:
    depends_on:
      - db
    image: tryexpress
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - /usr/src/app
    networks:
      - back

volumes: 
  my_volume:

networks:
  back:
    driver: bridge
